server:
  port: 9050
spring:
  application:
    name: registry

management:
  endpoint:
    health: /secure/health

eureka:
  client:
    register-with-eureka : false
    fetch-registry: false

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

