server:
  port: 9080
spring:
  application:
    name: user-settings

management:
  endpoint:
    health: /actuator/health
    info: /actuator/info

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    home-page-url: http://localhost:9080/
    nonSecurePort : ${server.port}
    #### alter these 2 in production
    nonSecurePortEnabled: true
    securePortEnabled: false
    #### alter these 2 in production
  client:
    healthcheck:
      enabled: true
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:9050/eureka/

info:
  app:
    Encoding: @project.build.sourceEncoding@
    Source: @java.version@
    Target: @java.version@
    Version: V1.0
    App-Name: ${spring.application.name}
    Desription: API for user trasaction, and history tracking.
    Micro-service-Registry: ${eureka.client.serviceUrl.defaultZone}
    Support-group : mail@bank.com

